package fr.epita.factorial.tests;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Assert;
import org.junit.Test;

import fr.epita.factorial.main.Factorial;

public class FactorialTest {
	
	@Test
	public void testCalculateFactorialOne()
	{
        assertEquals(1, Factorial.calculateFactorial(0));
	}

	@Test
	public void testNegativeFactorial()
	{
		try {
			Factorial.calculateFactorial(-1);
			fail("Should throw exception when calculating square root of a negative number");
			}catch(IllegalArgumentException aExp){
			    assert(aExp.getMessage().contains("negative number"));
	}
	@Test
	public void testCalculateFactorialFive()
	{
        assertEquals(120, Factorial.calculateFactorial(5));
	}
	@Test
	public void testCalculateFactorial()
	{
        assertEquals(1, Factorial.calculateFactorial(0));
	}
}
